### ISSUE TITLE
Can't move an element to the last position

### ISSUE THREAD

**Issue by davekiss** [AshesOfOwls/jquery.shapeshift#1]
Hi, great plugin, but having an issue (and, it seems to be occurring on your demo as well.)

I have a set of 100x100 boxes, but if I try to grab a box (let's call it box A) whose index is anything greater than the last box and move it to the last box (box Z), the boxes do not adjust to make room for the incoming box A. It seems to work at every position other than the last.

**Comment by AshesOfOwls** [comment]
Thanks, will get to this very soon.

**Comment by AshesOfOwls** [comment]
Got a temporary fix in, it isn't perfect positioning but it will work for now until I can figure out a more clean solution.

**Comment by AshesOfOwls** [comment]
I just did a semi-rewrite of the code, it should be working fine now.
