### ISSUE TITLE
Explain how to use a little more?

### ISSUE THREAD

**Issue by ryanhodson13** [AshesOfOwls/jquery.shapeshift#10]
I have the basic shape in place I don't now know how to creator the container with the divs in to attach the shapeshifte code. I can see you have written about targeting the container and all child elements will be looked after but can't see where I would write it? Can you help?

**Comment by kaiuhl** [comment]
Issues is not tech support :-1: 

Try stackoverflow?

**Comment by ryanhodson13** [comment]
Hi sorry I worked it out after I messaged you had to delete the demo stuff :-s
