### ISSUE TITLE
Known Issues - To Do List

### ISSUE THREAD

**Issue by AshesOfOwls** [AshesOfOwls/jquery.shapeshift#11]
This will be a continuously open thread that will contain a list of the issues that I am aware of and are trying to fix.
- [x] Ability to add a "trash" attribute which will destroy the selected element upon dropping.
- [x] Add attribute to disable animations upon initialization.
- [x] Make Padding X / Y modify the right / bottom sides instead of just from 0,0.
- [ ] Add support for elements that span multiple widths.
- [ ] Allow for single columns with 100% width children.
- [ ] Right align containers.

**Comment by K-Phoen** [comment]
I'm pretty interested in the "multiple width elements" feature. Do you have any release date in mind for this? I'm aware that it's not an easy feature, but it would be awesome to have it!

**Comment by AshesOfOwls** [comment]
I was playing around with it last week and was able to get it about 75% of the way done, but it's really messy code and I need to spend the next week refactoring it. I am going to try to get it done asap but in reality it will probably take me a week or two to finish completely. Hopefully it won't be too slow :)

**Comment by K-Phoen** [comment]
Good to know, thanks for your work :)

**Comment by Kaherdin** [comment]
Hello, first Thanks for this great plugin, it works fine, but I hope you can release soon an update with the multi width support ?
Do you have any news about this ?

**Comment by AshesOfOwls** [comment]
Yup, it's still coming along but taking longer than expected to fully flesh out. My next few weeks are going to be hectic personally so it was my goal to have it done before this upcoming sunday. Sorry for the wait!

**Comment by cardeo** [comment]
I have an interesting problem. The plugin works fine on first load of my homepage. However, if I navigate to say my about page, then come back home, all the images are stacked on top of each other. A page refresh will fix it but I'd rather avoid that. Have you encountered this before? Here's the site I'm working on http://13.cardeo.ca

**Comment by AshesOfOwls** [comment]
That is pretty strange, its a bit hard for me to troubleshoot only from the browser but it seems like the reason the elements stack is because the images haven't loaded yet. Without the images loaded all of the div elements have a very small height and shapeshift is using that to calculate the positions. Then the image load in, the heights change, and it looks like they are all stacked.

A way to get around this is to specify the height/width for each element in the CSS. Wrapping your code in a $(document).ready(function() {}) might also fix it.

**Comment by cardeo** [comment]
Thanks Scott, I'll try your solutions and let you know how it works out.

**Comment by AshesOfOwls** [comment]
Closing this thread in anticipation of 2.0 release.
