### ISSUE TITLE
missing px in bower component

### ISSUE THREAD

**Issue by alan-unravel** [AshesOfOwls/jquery.shapeshift#117]
Hi guys, just to let you know that the bower module has an error in the string to create a placeholder div that is fixed in  master. The width is missing the px at the end of the styles. Thanks

**Comment by ghosh** [comment]
:+1:  Thanks for opening an issue here for this. You just saved me hours of head scratching! This should be corrected in the bower version though.

**Comment by alan-unravel** [comment]
It is fixed now thank you. The error was not present in the master branch when I checked after I found it.
