### ISSUE TITLE
Is there any event for getting dropped element

### ISSUE THREAD

**Issue by rakeshmakam** [AshesOfOwls/jquery.shapeshift#119]
$(".feeds-content").shapeshift({
                dragClone: false,
                enableDrag: true,
                enableResize: false,
                enableAutoHeight: true,
                gutterX: 10, 
                gutterY: 10, 
                paddingX: 0,
                paddingY: 0,
            });

I tried this but not working

$('.feeds-content').on('ss-event-dropped', function (e, selected) {
        console.log($(selected).attr('id'))
});

**Comment by HaraldWalker** [comment]
ss-event-dropped ?

What are you dropping from where?
According to the API documentation you might be looking for ss-added or ss-rearranged.
https://github.com/McPants/jquery.shapeshift/wiki/2.0-api-documentation

**Comment by rakeshmakam** [comment]
Thanks a lot I got the event
