### ISSUE TITLE
if width of the child elements is 100%

### ISSUE THREAD

**Issue by kanakiyajay** [AshesOfOwls/jquery.shapeshift#13]
If you keep the width of the child elements which are to be dragged to be 100% , shapeshift doen't work.

**Comment by AshesOfOwls** [comment]
Could you explain a little further or provide an example? 

If I understand you correctly, Shapeshift is designed to only work with elements that are all the same fixed width. I have a branch up now which will include items that can span multiple columns but I won't be able to get that in for a few days.

**Comment by kanakiyajay** [comment]
Here is the jsFiddle example . It might be a problem in jquery UI position itself.
http://jsfiddle.net/bwenb/

https://github.com/kanakiyajay/dragdrop

The above is an example i have created.the drag widgets in the drop area should be positioned from 0px.
but they have started from 400px.

**Comment by AshesOfOwls** [comment]
I see, well it falls in an area that I haven't really tested out yet so I can't tell you if it will or will not work. I'll definitely take a look at it very soon.

**Comment by AshesOfOwls** [comment]
I have not tested this with version 2.0 which will be released tonight, however I will try it out before I do. Unfortunately this is a very low priority for me though.

**Comment by AshesOfOwls** [comment]
This should work in 2.0
