### ISSUE TITLE
Wordpress integration

### ISSUE THREAD

**Issue by n0vecento** [AshesOfOwls/jquery.shapeshift#15]
I tried to integrate shapeshift in wordpress, but, even if jquery.ui is correctly loaded, I get this alert: Query.shapeshift is trying to enable drag and drop but jQuery UI has not been included yet.

Any idea on where the problem could be?

**Comment by n0vecento** [comment]
As usual, immediately after I ask for help, I find the solution.
I enqueued scripts in functions.php
wp_enqueue_script( 'jquery-ui-core' );
wp_enqueue_script( 'jquery-ui-draggable' );
wp_enqueue_script( 'jquery-ui-droppable' );
and now it works.

**Comment by AshesOfOwls** [comment]
:)

**Comment by gitbenb** [comment]
amazing.

what about a WordPress plug in?
