### ISSUE TITLE
Right align containers

### ISSUE THREAD

**Issue by PangbornIdentity** [AshesOfOwls/jquery.shapeshift#16]
Any plans to include Right align drop containers?
Right now it appears we can center the grid, or have it left aligned.
thoughts?
-Rich

**Comment by AshesOfOwls** [comment]
Very easy to implement, I'll include it in the to-do list for the next release, which should be by this sunday.

**Comment by PangbornIdentity** [comment]
@McPants 
Is this still on the To Do list?

**Comment by AshesOfOwls** [comment]
This should be working using the option align: 

``` coffeescript
$(".container").shapeshift
    align: "right"
```
