### ISSUE TITLE
Drag selector

### ISSUE THREAD

**Issue by scux** [AshesOfOwls/jquery.shapeshift#20]
Hi,

very good plugin that i'm trying to use.
I was wondering if it's possible to specify the drag selector on the options ?

for example :

``` html
<div id="boxes">
     <div class="box">
          <div>content 1</div>
          <div class="handle">handle me</div>
     </div>
     <div class="box">
          <div>content 2</div>
          <div class="handle">handle me</div>
     </div>
</div>
```

``` javascript
$('#boxes').shapeshift({
     dragHandler: '.handle'
});
```

**Comment by AshesOfOwls** [comment]
Definitely, I'm currently in the middle of a total rewrite of the code and I should be able to get this in. I can't specify a timeframe on this because each time I do I tend to miss it, heh. Shouldn't be too long though.

**Comment by AshesOfOwls** [comment]
I am trying to release version 2.0 tonight. I will see if I can get this implemented before its release.

**Comment by AshesOfOwls** [comment]
This has been added to 2.0 although it will still center the object after the handle has been clicked. It may take me a while to get that sorted out. Closing this thread, you can follow the progress of 2.0 in the Multiwidth issue.
