### ISSUE TITLE
Docs should mention dependency on query-ui

### ISSUE THREAD

**Issue by Pumpapa** [AshesOfOwls/jquery.shapeshift#29]
Out of the box I get an "Uncaught TypeError: Object [object Object] has no method 'draggable' jquery.shapeshift.js:399"
That's defined in "query-ui.min.js", not mentioned in the docs but apparently needed.

**Comment by AshesOfOwls** [comment]
The dependencies for Shapeshift are [listed here](https://github.com/McPants/jquery.shapeshift#dependencies), sorry for the confusion. You can also turn off Drag and Drop by setting both the options "enableDrag" and "enableCrossDrop" to false.
