### ISSUE TITLE
Host releases on cdnjs

### ISSUE THREAD

**Issue by mcilrain** [AshesOfOwls/jquery.shapeshift#31]
I use [cdnjs](http://cdnjs.com/) a lot, mostly for the convenience of just copy/pasting a URL to try out new libraries, it would be cool to see this library there.

**Comment by AshesOfOwls** [comment]
WIll do, thanks for the suggestion.

**Comment by AshesOfOwls** [comment]
Pull request submitted.

**Comment by AshesOfOwls** [comment]
Posting here to remind myself to add this information to the readme once the pull request is accepted.

**Comment by AshesOfOwls** [comment]
Merge success!
