### ISSUE TITLE
Display draggable children everywhere

### ISSUE THREAD

**Issue by TimDaub** [AshesOfOwls/jquery.shapeshift#32]
Hi,

just a quick question. How can i achive that my draggable children are on top of every container i have on my page?
![clipshape](https://f.cloud.github.com/assets/2758453/424826/9e019b36-ad98-11e2-978c-d0e49e522266.png)
Right now they just disappear when i drag them out of the parent container.

Greetings

**Comment by TimDaub** [comment]
I found it out myself: If you set your parent boxes to overflow:hidden then it will disappear at the border.
So for fixing this just delete the overflow property of your parent box.

**Comment by AshesOfOwls** [comment]
Sweet, I actually bet there are some use cases where it would be good to have it disappear at the border which I never thought of so that might be cool in the future.

Is it ok if I close this thread?

**Comment by TimDaub** [comment]
Yes :)
PS: Thank you for jq Shapeshift by the way

**Comment by AshesOfOwls** [comment]
No problemo, it's a fun project. Makes it even more fun since people are actually using it haha
