### ISSUE TITLE
jsFiddle examples?

### ISSUE THREAD

**Issue by senner007** [AshesOfOwls/jquery.shapeshift#36]
Greetings.

Could you perhaps post a few fiddle examples to toy around with?

**Comment by AshesOfOwls** [comment]
Sure can, but I am going to need a little bit of time to do so. I have a lot on my plate right now unfortunately.

**Comment by jackmarketon** [comment]
Hey, I can help write up a couple fiddle examples, especially implementing sorting. (I'll look into it this weekend)

**Comment by AshesOfOwls** [comment]
Thanks jack, I'll create a section in the readme for those examples when you get them up. Also, if anyone has ideas for a specific example they would like to see please feel free to list them off.

**Comment by senner007** [comment]
Much appreciated.

**Comment by AshesOfOwls** [comment]
I updated the demo with a new format that is easier for me to maintain over the long run. The two examples I have are just a simple two container setup and a mosaic setup. Both of them have Gists at the top of the page and I will also link to some jsfiddles for them soon.

Are there any specific examples you would like to see? I will try to add as many as I can.

**Comment by AshesOfOwls** [comment]
Each example now has a JSFiddle associated with it

http://mcpants.github.io/jquery.shapeshift/

http://mcpants.github.io/jquery.shapeshift/#/mosaic

**Comment by AshesOfOwls** [comment]
Added a trash demo

http://mcpants.github.io/jquery.shapeshift/#/trash

Going to close this. Feel free to suggest any new examples you would want to see. I have made it so the demo is very easy to update with new ones.
