### ISSUE TITLE
Save State of DIVs

### ISSUE THREAD

**Issue by januszjasinski** [AshesOfOwls/jquery.shapeshift#38]
I like the look of the switch of the dmeo that shows the index status of the DIVs - has the function behind this been made public?

I digress - what's the easiest way to save the state of the DIVs after each drag 'n' drop? I'm designing a customisable dashboard and the elements can be shifted around

Thanks

**Comment by AshesOfOwls** [comment]
The way Shapeshift currently works is by literally changing the index position of the element as you drag it around. Therefore if you had this HTML setup:

``` html
<div class="container">
  <div data-id="2"></div>
  <div data-id="3"></div>
  <div data-id="1"></div>
  <div data-id="4"></div>
</div>
```

To find out the index position of each element, you would do this:

``` javascript
$('.container').children().each(function() {
  $(this).index() // Retrieve the index position
  $(this).data("id") // Get the id assigned to the div
});
```

Shapeshift also has some events that you can listen for on the container. Examples for these similar to the one above can be found at the [bottom of the version 2.0 docs](https://github.com/McPants/jquery.shapeshift/wiki/2.0-api-documentation#event-listening-examples).

Feel free to ask any more questions you need.
