### ISSUE TITLE
Touch Enabled

### ISSUE THREAD

**Issue by januszjasinski** [AshesOfOwls/jquery.shapeshift#39]
Would be good to show an example of the touch enabled code for newbies

**Comment by AshesOfOwls** [comment]
This actually is just a patch for jQuery UI called jQuery Touch Punch. Including it after jQuery UI will allow for touch events to be used without actually having to change any settings.

Their official website is here: http://touchpunch.furf.com/

I'm going to close this but I will explicitly include an example in at least one of the demos mentioned in #40
