### ISSUE TITLE
Whole Examples

### ISSUE THREAD

**Issue by januszjasinski** [AshesOfOwls/jquery.shapeshift#40]
Examples on jsfiddle are fine but it won't easily enable a newbie to use ShapeShift themselves. Can you create demo pages with various options and make it available for download?

**Comment by AshesOfOwls** [comment]
Definitely, let me see if I can arrange something like that today as I am spending this week trying to optimize the demos. I think I know a good solution to this.

If you have any specific ideas for the demo please let me know, there are a lot of different use cases that Shapeshift can fall under and I'm not exactly sure which ones people would like to see the most.

**Comment by AshesOfOwls** [comment]
Just committed the new demos and made the old /demo folder only accessible through the gh-pages branch.

You can find them in the demos folder, all of them are barebones single page html examples. Let me know if you would like for any other examples to be created.
