### ISSUE TITLE
PaddingX

### ISSUE THREAD

**Issue by GiovaneBueno** [AshesOfOwls/jquery.shapeshift#41]
Hello, in relation to paddingX, I'm using it with value 0, in maximized screen everything went ok, but minimizing the screen, it is not equal, I can change  some property for that or is it a pattern?

Used 'align: "left"', it set the left side, there would have both sides as well? Right and left?

Another question, in relation to IE8 occurs interference ?

Grateful !

**Comment by GiovaneBueno** [comment]
Problem solved, used a calculation to change the value of "gutterX".

**Comment by AshesOfOwls** [comment]
Ah dynamic gutters, great idea!

I'm glad you solved it. I am going to keep this open and mark it for version 3.0 as a core feature.

**Comment by GiovaneBueno** [comment]
Glad to contribute to shapeshift jquery, am always watching the versions! Grateful.

**Comment by AshesOfOwls** [comment]
This is now in 3.0 and is working quite well. Should be released within the next month.
