### ISSUE TITLE
License Type?

### ISSUE THREAD

**Issue by ghost** [AshesOfOwls/jquery.shapeshift#6]

**Comment by AshesOfOwls** [comment]
MIT :)

http://opensource.org/licenses/MIT

**Comment by ghost** [comment]
hey, thank you for the update, Scott! Nice work on Shapeshift - blogged about it here: http://www.functionn.in/2012/12/jquery-shapeshift-plugin-to-dynamically.html :-)

**Comment by AshesOfOwls** [comment]
Thanks man, It's been awesome seeing such a warm welcome to it.

**Comment by ghost** [comment]
I'm glad for you man - good work deserves recognition, keep it up and if you release any other jQuery plugin or libraries, just drop me a message, I'll feature it ;-)
