### ISSUE TITLE
.map() issue in IE8

### ISSUE THREAD

**Issue by Perhn** [AshesOfOwls/jquery.shapeshift#60]
Hi McPants
First of all... amazing stuff you have made with the Shapeshift... 
but I did run in to an issue with this piece of code in IE8:
Line 577:
        augmented_array = array.map(function (val, index) {
            return [val, index];
        });

It made the view of the block collapse on top of each other, because IE couldn't read the  map() function.

I got it to work by changing the code into:
        augmented_array = $.map(array, function (val, index) {
            return [[val, index]];
        });

Don't know if I'm the only having this problem, but thought I would let you know. :0)

**Comment by AshesOfOwls** [comment]
Thanks for letting me know. V2.0 is already pretty borked in IE8 so I think I am going to push for this change in 3.0

**Comment by Perhn** [comment]
yep, unfortunately there are still a lot of people  using IE8, it would make life easier if there only where one browser and everyone had the latest version :)
Please let me know if you need any help for testing. 
Thanks again
Per

**Comment by AshesOfOwls** [comment]
I will have this listed in the 3.0 todo so I will make sure not to repeat this mistake in the new version. Thanks again Perhn.
