### ISSUE TITLE
Inconsistent Gutter Behavior when  doing re-size if  children width in  is % 

### ISSUE THREAD

**Issue by way2nikhil** [AshesOfOwls/jquery.shapeshift#69]
Hi 
I am facing an issue .Can you check the following jsbin

http://jsbin.com/irePufI/7

Please observe when the browser is re sized(less size,more size) the gutter space between childs (increase ,decrease) respectively even though it is 0 and was looking fine before resize.

Second observation : If i refresh the page in resized  browser , the gutterx is restored.

I tried with both enableResize:false also, but same behaviour.

Can you help if it can be resolved.

**Comment by AshesOfOwls** [comment]
At this time Shapeshift doesn't support percentage width children, but that will change in 3.0 once I can get it out the door.
