### ISSUE TITLE
Drag item into empty container

### ISSUE THREAD

**Issue by 16n** [AshesOfOwls/jquery.shapeshift#7]
First I want to say thank you for the great work you've done.
But I discovered a little problem. If you have two containers and there are items in both, you can drag items between them without any problem. But if you have an empty container and you want to drag something in there it won't work.

Thanks,
Jonas

**Comment by AshesOfOwls** [comment]
Looking into it now!

**Comment by AshesOfOwls** [comment]
The jQuery droppable zones are acting pretty wonky, I can probably get it fixed by the end of the month.

**Comment by AshesOfOwls** [comment]
Should be good with this fix.

**Comment by 16n** [comment]
I'll check it. Thanks!

**Comment by 16n** [comment]
Fixed. Thank you very much works great!

**Comment by sajumani** [comment]
with this min file, trash is not working...

**Comment by gabryk91** [comment]
I'm facing the same issue
