### ISSUE TITLE
FPOImg.com

### ISSUE THREAD

**Issue by kylehayes** [AshesOfOwls/jquery.shapeshift#9]
Thank you for using FPOImg.com! Your usage of the site as well as others encouraged me to update its look and features. You'll notice your example page has better looking placement images now. You can also check out fpoimg.com to see some of the others you can do now as well as the examples page.

Thanks!

**Comment by AshesOfOwls** [comment]
Very cool, I love it! I updated the demo to showcase it more :)

**Comment by kylehayes** [comment]
Excellent—looks great!
